version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      -  /home/node/app/node_modules
      - ~/react-app:/home/node/app