name: Test app
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: login to docker
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: build docker
      - run: docker build -t cygnetops/react-test -f dockerfile.dev .
      - name: run tests
      - run: docker run -e CI=true cygnetops/react-test npm test