name: ci-react-app-test

on:
  pull_request:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build docker
        run: docker build -t cygnetops/react-test -f dockerfile.dev .
      - name: run tests
        run: docker run -e CI=true cygnetops/react-test npm run test